# Generated by Django 3.0.3 on 2020-07-13 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_studentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='nesclassmodel',
            name='cid',
            field=models.IntegerField(auto_created=True, default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='si',
            field=models.IntegerField(auto_created=True, default=0),
        ),
        migrations.CreateModel(
            name='EnrokedCourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.ManyToManyField(to='app1.NesclassModel')),
                ('studentid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.StudentMOdel')),
            ],
        ),
    ]
