# Generated by Django 3.0.3 on 2020-07-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200713_1826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrokedCourseModel',
        ),
    ]
