# Generated by Django 3.0.3 on 2020-07-14 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_delete_enrokedcoursemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrokedCourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.NesclassModel')),
                ('sid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.StudentMOdel')),
            ],
        ),
    ]
