# Generated by Django 3.0.3 on 2020-07-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200714_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrokedcoursemodel',
            name='cn',
        ),
        migrations.AddField(
            model_name='enrokedcoursemodel',
            name='cn',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.NesclassModel'),
        ),
    ]
