# Generated by Django 3.0.3 on 2020-07-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20200714_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrokedcoursemodel',
            name='sid',
        ),
    ]
