# Generated by Django 3.0.3 on 2020-07-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_enrokedcoursemodel_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrokedcoursemodel',
            name='sid',
            field=models.IntegerField(default=0),
        ),
    ]
