# Generated by Django 3.0.3 on 2020-07-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_enrokedcoursemodel_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nesclassmodel',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='si',
        ),
    ]
