# Generated by Django 3.0.3 on 2020-07-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20200717_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrokedcoursemodel',
            name='sid',
        ),
        migrations.AddField(
            model_name='enrokedcoursemodel',
            name='sid',
            field=models.ManyToManyField(default=0, to='app1.StudentMOdel'),
        ),
    ]
