# Generated by Django 3.0.3 on 2020-07-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20200717_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrokedcoursemodel',
            name='cn',
            field=models.IntegerField(default=0),
        ),
    ]
